package pl.wit.lab2;

import org.junit.Test;

public class TextStatisticTest {

	@Test
	public void textStatsTest() {
		TextStatistic textStat = new TextStatistic("\r\n"
				+ "\r\n"
				+ "Litwo! Ojczyzno moja! ty jesteś jak zdrowie.\r\n"
				+ "\r\n"
				+ "Ile cię trzeba cenić, ten tylko się dowie,\r\n"
				+ "\r\n"
				+ "Kto cię stracił. Dziś piękność twą w całej ozdobie\r\n"
				+ "\r\n"
				+ "Widzę i opisuję, bo tęsknię po tobie.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Panno Święta, co jasnej bronisz Częstochowy\r\n"
				+ "\r\n"
				+ "I w Ostrej świecisz Bramie! Ty, co gród zamkowy\r\n"
				+ "\r\n"
				+ "Nowogródzki ochraniasz z jego wiernym ludem!\r\n"
				+ "\r\n"
				+ "Jak mnie dziecko do zdrowia powróciłaś cudem\r\n"
				+ "\r\n"
				+ "(Gdy od płaczącej matki pod Twoją opiekę\r\n"
				+ "\r\n"
				+ "Ofiarowany, martwą podniosłem powiekę\r\n"
				+ "\r\n"
				+ "I zaraz mogłem pieszo do Twych świątyń progu\r\n"
				+ "\r\n"
				+ "Iść za wrócone życie podziękować Bogu),\r\n"
				+ "\r\n"
				+ "Tak nas powrócisz cudem na Ojczyzny łono.\r\n"
				+ "\r\n"
				+ "Tymczasem przenoś moję duszę utęsknioną\r\n"
				+ "\r\n"
				+ "Do tych pagórków leśnych, do tych łąk zielonych,\r\n"
				+ "\r\n"
				+ "Szeroko nad błękitnym Niemnem rozciągnionych;\r\n"
				+ "\r\n"
				+ "Do tych pól malowanych zbożem rozmaitem,\r\n"
				+ "\r\n"
				+ "Wyzłacanych pszenicą, posrebrzanych żytem;\r\n"
				+ "\r\n"
				+ "Gdzie bursztynowy świerzop, gryka jak śnieg biała,\r\n"
				+ "\r\n"
				+ "Gdzie panieńskim rumieńcem dzięcielina pała,\r\n"
				+ "\r\n"
				+ "A wszystko przepasane, jakby wstęgą, miedzą\r\n"
				+ "\r\n"
				+ "Zieloną, na niej z rzadka ciche grusze siedzą.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Śród takich pól przed laty, nad brzegiem ruczaju,\r\n"
				+ "\r\n"
				+ "Na pagórku niewielkim, we brzozowym gaju,\r\n"
				+ "\r\n"
				+ "Stał dwór szlachecki, z drzewa, lecz podmurowany;\r\n"
				+ "\r\n"
				+ "Świeciły się z daleka pobielane ściany,\r\n"
				+ "\r\n"
				+ "Tym bielsze, że odbite od ciemnej zieleni\r\n"
				+ "\r\n"
				+ "Topoli, co go bronią od wiatrów jesieni.\r\n"
				+ "\r\n"
				+ "Dóm mieszkalny niewielki, lecz zewsząd chędogi,\r\n"
				+ "\r\n"
				+ "I stodołę miał wielką, i przy niej trzy stogi\r\n"
				+ "\r\n"
				+ "Użątku, co pod strzechą zmieścić się nie może;\r\n"
				+ "\r\n"
				+ "Widać, że okolica obfita we zboże,\r\n"
				+ "\r\n"
				+ "I widać z liczby kopic, co wzdłuż i wszerz smugów\r\n"
				+ "\r\n"
				+ "Świecą gęsto jak gwiazdy, widać z liczby pługów\r\n"
				+ "\r\n"
				+ "Orzących wcześnie łany ogromne ugoru,\r\n"
				+ "\r\n"
				+ "Czarnoziemne, zapewne należne do dworu,\r\n"
				+ "\r\n"
				+ "Uprawne dobrze na kształt ogrodowych grządek:\r\n"
				+ "\r\n"
				+ "Że w tym domu dostatek mieszka i porządek.\r\n"
				+ "\r\n"
				+ "Brama na wciąż otwarta przechodniom ogłasza,\r\n"
				+ "\r\n"
				+ "Że gościnna i wszystkich w gościnę zaprasza.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Właśnie dwókonną bryką wjechał młody panek\r\n"
				+ "\r\n"
				+ "I obiegłszy dziedziniec zawrócił przed ganek,\r\n"
				+ "\r\n"
				+ "Wysiadł z powozu; konie porzucone same,\r\n"
				+ "\r\n"
				+ "Szczypiąc trawę ciągnęły powoli pod bramę.\r\n"
				+ "\r\n"
				+ "We dworze pusto, bo drzwi od ganku zamknięto\r\n"
				+ "\r\n"
				+ "Zaszczepkami i kołkiem zaszczepki przetknięto.\r\n"
				+ "\r\n"
				+ "Podróżny do folwarku nie biegł sług zapytać;\r\n"
				+ "\r\n"
				+ "Odemknął, wbiegł do domu, pragnął go powitać.\r\n"
				+ "\r\n"
				+ "Dawno domu nie widział, bo w dalekim mieście\r\n"
				+ "\r\n"
				+ "Kończył nauki, końca doczekał nareszcie.\r\n"
				+ "\r\n"
				+ "Wbiega i okiem chciwie ściany starodawne\r\n"
				+ "\r\n"
				+ "Ogląda czule, jako swe znajome dawne.\r\n"
				+ "\r\n"
				+ "Też same widzi sprzęty, też same obicia,\r\n"
				+ "\r\n"
				+ "Z któremi się zabawiać lubił od powicia;\r\n"
				+ "\r\n"
				+ "Lecz mniej wielkie, mniej piękne, niż się dawniej zdały.\r\n"
				+ "\r\n"
				+ "I też same portrety na ścianach wisiały.\r\n"
				+ "\r\n"
				+ "Tu Kościuszko w czamarce krakowskiej, z oczyma\r\n"
				+ "\r\n"
				+ "Podniesionymi w niebo, miecz oburącz trzyma;\r\n"
				+ "\r\n"
				+ "Takim był, gdy przysięgał na stopniach ołtarzów,\r\n"
				+ "\r\n"
				+ "Że tym mieczem wypędzi z Polski trzech mocarzów\r\n"
				+ "\r\n"
				+ "Albo sam na nim padnie. Dalej w polskiej szacie\r\n"
				+ "\r\n"
				+ "Siedzi Rejtan żałośny po wolności stracie,\r\n"
				+ "\r\n"
				+ "W ręku trzymna nóż, ostrzem zwrócony do łona,\r\n"
				+ "\r\n"
				+ "A przed nim leży Fedon i żywot Katona.\r\n"
				+ "\r\n"
				+ "Dalej Jasiński, młodzian piękny i posępny,\r\n"
				+ "\r\n"
				+ "Obok Korsak, towarzysz jego nieodstępny,\r\n"
				+ "\r\n"
				+ "Stoją na szańcach Pragi, na stosach Moskali,\r\n"
				+ "\r\n"
				+ "Siekąc wrogów, a Praga już się wkoło pali.\r\n"
				+ "\r\n"
				+ "Nawet stary stojący zegar kurantowy\r\n"
				+ "\r\n"
				+ "W drewnianej szafie poznał u wniścia alkowy\r\n"
				+ "\r\n"
				+ "I z dziecinną radością pociągnął za sznurek,\r\n"
				+ "\r\n"
				+ "By stary Dąbrowskiego usłyszeć mazurek.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Biegał po całym domu i szukał komnaty,\r\n"
				+ "\r\n"
				+ "Gdzie mieszkał, dzieckiem będąc, przed dziesięciu laty.\r\n"
				+ "\r\n"
				+ "Wchodzi, cofnął się, toczył zdumione źrenice\r\n"
				+ "\r\n"
				+ "Po ścianach: w tej komnacie mieszkanie kobiéce?\r\n"
				+ "\r\n"
				+ "Któż by tu mieszkał? Stary stryj nie był żonaty,\r\n"
				+ "\r\n"
				+ "A ciotka w Petersburgu mieszkała przed laty.\r\n"
				+ "\r\n"
				+ "To nie był ochmistrzyni pokój! Fortepiano?\r\n"
				+ "\r\n"
				+ "Na niem noty i książki; wszystko porzucano\r\n"
				+ "\r\n"
				+ "Niedbale i bezładnie; nieporządek miły!\r\n"
				+ "\r\n"
				+ "Niestare były rączki, co je tak rzuciły.\r\n"
				+ "\r\n"
				+ "Tuż i sukienka biała, świeżo z kołka zdjęta\r\n"
				+ "\r\n"
				+ "Do ubrania, na krzesła poręczu rozpięta.\r\n"
				+ "\r\n"
				+ "A na oknach donice z pachnącymi ziołki,\r\n"
				+ "\r\n"
				+ "Geranium, lewkonija, astry i fijołki.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Podróżny stanął w jednym z okien - nowe dziwo:\r\n"
				+ "\r\n"
				+ "W sadzie, na brzegu niegdyś zarosłym pokrzywą,\r\n"
				+ "\r\n"
				+ "Był maleńki ogródek, ścieżkami porznięty,\r\n"
				+ "\r\n"
				+ "Pełen bukietów trawy angielskiej i mięty.\r\n"
				+ "\r\n"
				+ "Drewniany, drobny, w cyfrę powiązany płotek\r\n"
				+ "\r\n"
				+ "Połyskał się wstążkami jaskrawych stokrotek.\r\n"
				+ "\r\n"
				+ "Grządki widać, że były świeżo polewane;\r\n"
				+ "\r\n"
				+ "Tuż stało wody pełne naczynie blaszane,\r\n"
				+ "\r\n"
				+ "Ale nigdzie nie widać było ogrodniczki;\r\n"
				+ "\r\n"
				+ "Tylko co wyszła; jeszcze kołyszą się drzwiczki\r\n"
				+ "\r\n"
				+ "Świeżo trącone; blisko drzwi ślad widać nóżki\r\n"
				+ "\r\n"
				+ "Na piasku, bez trzewika była i pończoszki;\r\n"
				+ "\r\n"
				+ "Na piasku drobnym, suchym, białym na kształt śniegu,\r\n"
				+ "\r\n"
				+ "Ślad wyraźny, lecz lekki; odgadniesz, że w biegu\r\n"
				+ "\r\n"
				+ "Chybkim był zostawiony nóżkami drobnemi\r\n"
				+ "\r\n"
				+ "Od kogoś, co zaledwie dotykał się ziemi.\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "Podróżny długo w oknie stał patrząc, dumając,\r\n"
				+ "\r\n"
				+ "Wonnymi powiewami kwiatów oddychając,\r\n"
				+ "\r\n"
				+ "Oblicze aż na krzaki fijołkowe skłonił,\r\n"
				+ "\r\n"
				+ "Oczyma ciekawymi po drożynach gonił\r\n"
				+ "\r\n"
				+ "I znowu je na drobnych śladach zatrzymywał,\r\n"
				+ "\r\n"
				+ "Myślał o nich i, czyje były, odgadywał.\r\n"
				+ "\r\n"
				+ "Przypadkiem oczy podniósł, i tuż na parkanie\r\n"
				+ "\r\n"
				+ "Stała młoda dziewczyna. - Białe jej ubranie\r\n"
				+ "\r\n"
				+ "Wysmukłą postać tylko aż do piersi kryje,\r\n"
				+ "\r\n"
				+ "Odsłaniając ramiona i łabędzią szyję.\r\n"
				+ "\r\n"
				+ "W takim Litwinka tylko chodzić zwykła z rana,\r\n"
				+ "\r\n"
				+ "W takim nigdy nie bywa od mężczyzn widziana:\r\n"
				+ "\r\n"
				+ "Więc choć świadka nie miała, założyła ręce\r\n"
				+ "\r\n"
				+ "Na piersiach, przydawając zasłony sukience.\r\n"
				+ "\r\n"
				+ "Włos w pukle nie rozwity, lecz w węzełki małe\r\n"
				+ "\r\n"
				+ "Pokręcony, schowany w drobne strączki białe,\r\n"
				+ "\r\n"
				+ "Dziwnie ozdabiał głowę, bo od słońca blasku\r\n"
				+ "\r\n"
				+ "Świecił się, jak korona na świętych obrazku.\r\n"
				+ "\r\n"
				+ "Twarzy nie było widać. Zwrócona na pole\r\n"
				+ "\r\n"
				+ "Szukała kogoś okiem, daleko, na dole;\r\n"
				+ "\r\n"
				+ "Ujrzała, zaśmiała się i klasnęła w dłonie,\r\n"
				+ "\r\n"
				+ "Jak biały ptak zleciała z parkanu na błonie\r\n"
				+ "\r\n"
				+ "I wionęła ogrodem przez płotki, przez kwiaty,\r\n"
				+ "\r\n"
				+ "I po desce opartej o ścianę komnaty,\r\n"
				+ "\r\n"
				+ "Nim spostrzegł się, wleciała przez okno, świecąca,\r\n"
				+ "\r\n"
				+ "Nagła, cicha i lekka jak światłość miesiąca.\r\n"
				+ "\r\n"
				+ "Nócąc chwyciła suknie, biegła do zwierciadła;\r\n"
				+ "\r\n"
				+ "Wtem ujrzała młodzieńca i z rąk jej wypadła\r\n"
				+ "\r\n"
				+ "Suknia, a twarz od strachu i dziwu pobladła.\r\n"
				+ "\r\n"
				+ "Twarz podróżnego barwą spłonęła rumianą\r\n"
				+ "\r\n"
				+ "Jak obłok, gdy z jutrzenką napotka się ranną;\r\n"
				+ "\r\n"
				+ "Skromny młodzieniec oczy zmrużył i przysłonił,\r\n"
				+ "\r\n"
				+ "Chciał coś mówić, przepraszać, tylko się ukłonił\r\n"
				+ "\r\n"
				+ "I cofnął się; dziewica krzyknęła boleśnie,\r\n"
				+ "\r\n"
				+ "Niewyraźnie, jak dziecko przestraszone we śnie;\r\n"
				+ "\r\n"
				+ "Podróżny zląkł się, spójrzał, lecz już jej nie było.\r\n"
				+ "\r\n"
				+ "Wyszedł zmieszany i czuł, że serce mu biło\r\n"
				+ "\r\n"
				+ "Głośno, i sam nie wiedział, czy go miało śmieszyć\r\n"
				+ "\r\n"
				+ "To dziwaczne spotkanie, czy wstydzić, czy cieszyć.");
		
		System.out.println("liczba wyrazów=".concat(String.valueOf(textStat.getWordsCount())));
		System.out.println("Statystyka:\n"+textStat.getTextStatisticsInfo());
	}

}
